### ISSUE TITLE
Zusätzlich lokale Blacklist? 

### ISSUE THREAD

**Issue by mmalte** [ffruhr/fastdbl#3]
Habt ihr zusätzlich zu diesen hier noch lokale sperren? 

Hintergrund ist dass ich gerne geographisch völlig falsche Knoten (in der Nordsee, an der Mosel) zu denen ich keinen Kontakt Adresse habe sperren möchte. 

Soll ich das über dieses repo machen oder eine zusätzliche lokale Liste führen.

**Comment by pberndro** [comment]
Das hier ist das "offizielle" und einzige uns bekannte Repro beim FFRL mit einer Blackliste.
